.PHONY: install_db create_user create_db

MYSQL_ROOT_PASS=root_password
MYSQL_USER=Testuser
MYSQL_USER_PASS=13243546Aa@
MYSQL_DATABASE=Base4Test
MYSQL_TABLE=HashTable

install_db:
    sudo apt-get install -y mysql-server libmysqlclient-dev

create_user:
    mysql -uroot -p$(MYSQL_ROOT_PASS) -e "CREATE USER '$(MYSQL_USER)'@'localhost' IDENTIFIED BY '$(MYSQL_USER_PASS)'"
    mysql -uroot -p$(MYSQL_ROOT_PASS) -e "GRANT ALL PRIVILEGES ON *.* TO '$(MYSQL_USER)'@'localhost'"
    
create_db:
    mysql -uroot -p$(MYSQL_ROOT_PASS) -e "CREATE DATABASE $(MYSQL_DATABASE)"
    mysql -uroot -p$(MYSQL_ROOT_PASS) -e "USE $(MYSQL_DATABASE); CREATE TABLE $(MYSQL_TABLE) (string VARCHAR(255), hash VARCHAR(255))"
